# fly.toml app configuration file generated for fly-notification-agent on 2023-05-13T16:04:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fly-notification-agent"
primary_region = "ams"

[env]
  PORT = "8080"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 0
